### ISSUE TITLE
In Video call audio track is not working

### ISSUE THREAD

**Issue by 2sidd** [philnash/video-collaboration#1]
In google chrome

**Comment by philnash** [comment]
Hi @2sidd, can you give me a bit more information here, please? When you say the audio track isn't working, what do you mean? Are there any errors in the dev tools? Does it work in another browser? Have you given permission to the browser to use your microphone?

Any details you share can help us fix this.

**Comment by 2sidd** [comment]
When you say the audio track isn't working, what do you mean?
 In Video call I am not able to listen video. I have tried this on 1) local machine 2) I have deployed this on a azure server.. from both places I can not listen audio on video call.

**Comment by philnash** [comment]
How about my other questions?

**Comment by 2sidd** [comment]
Are there any errors in the dev tools? 
No
Does it work in another browser?
No, I have tried it using Chrome and IE 

Have you given permission to the browser to use your microphone?
 Yes
 
 It works with  main branch , I am facing this issue with whiteboard branch

**Comment by philnash** [comment]
In the whiteboard branch it seems I muted the participants: https://github.com/philnash/video-collaboration/commit/6a9f781afa6140d2b98d6d6830511dd5d52406c3

Remove that line and it will work again!

**Comment by 2sidd** [comment]
@philnash it worked. Thank you.
Can you Please write a blog on video collaboration. Or extend your react hooks video application with features like whiteboard, text chat. File sharing, co browsing.
